"""add cook_sessions table

Revision ID: 5ea2998c906c
Revises: f187467f5c47
Create Date: 2026-08-04 00:31:28.468721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea2998c906c'
down_revision: Union[str, None] = 'f187467f5c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cook_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cook_sessions_recipe_id'), 'cook_sessions', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_cook_sessions_session_id'), 'cook_sessions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cook_sessions_session_id'), table_name='cook_sessions')
    op.drop_index(op.f('ix_cook_sessions_recipe_id'), table_name='cook_sessions')
    op.drop_table('cook_sessions')
    # ### end Alembic commands ###
