"""recipes에 description, servings, difficulty, tip 추가

Revision ID: d2814e88228e
Revises: 5ea2998c906c
Create Date: 2026-08-06 01:24:31.213817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2814e88228e'
down_revision: Union[str, None] = '5ea2998c906c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('tip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_check_constraint(
        'ck_recipes_difficulty',
        'recipes',
        "difficulty IS NULL OR difficulty IN ('easy', 'normal', 'hard')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_recipes_difficulty', 'recipes', type_='check')
    op.drop_column('recipes', 'tip')
    op.drop_column('recipes', 'difficulty')
    op.drop_column('recipes', 'servings')
    op.drop_column('recipes', 'description')
    # ### end Alembic commands ###
