"""drop cook_sessions table

Revision ID: da37dca1713e
Revises: d2814e88228e
Create Date: 2026-08-10 18:29:47.659404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da37dca1713e'
down_revision: Union[str, None] = 'd2814e88228e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cook_sessions_recipe_id'), table_name='cook_sessions')
    op.drop_index(op.f('ix_cook_sessions_session_id'), table_name='cook_sessions')
    op.drop_table('cook_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cook_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('cook_sessions_recipe_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], name=op.f('cook_sessions_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cook_sessions_pkey'))
    )
    op.create_index(op.f('ix_cook_sessions_session_id'), 'cook_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_cook_sessions_recipe_id'), 'cook_sessions', ['recipe_id'], unique=False)
    # ### end Alembic commands ###
