"""initial schema

Revision ID: f187467f5c47
Revises: 
Create Date: 2026-07-31 21:02:49.049348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f187467f5c47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('browser_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_users_browser_uuid'), 'anonymous_users', ['browser_uuid'], unique=True)
    op.create_table('ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_is_top'), 'ingredients', ['is_top'], unique=False)
    op.create_index(op.f('ix_ingredients_normalized_name'), 'ingredients', ['normalized_name'], unique=True)
    op.create_table('llm_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingredients_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed_recipes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_cache_ingredients_hash'), 'llm_cache', ['ingredients_hash'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cooking_time_min', sa.Integer(), nullable=False),
    sa.Column('is_llm_generated', sa.Boolean(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_ingredient_id'), 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('anonymous_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anonymous_user_id'], ['anonymous_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_anonymous_user_id'), 'user_sessions', ['anonymous_user_id'], unique=False)
    op.create_table('fridge_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('freshness_status', sa.String(), nullable=False),
    sa.Column('food_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("freshness_status IN ('fresh', 'near_expiry', 'expired')", name='ck_fridge_items_freshness_status'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridge_items_ingredient_id'), 'fridge_items', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_fridge_items_session_id'), 'fridge_items', ['session_id'], unique=False)
    op.create_table('interaction_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_logs_created_at'), 'interaction_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_interaction_logs_event_type'), 'interaction_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_interaction_logs_recipe_id'), 'interaction_logs', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_interaction_logs_session_id'), 'interaction_logs', ['session_id'], unique=False)
    op.create_table('recommendation_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('ingredients_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_requests_ingredients_hash'), 'recommendation_requests', ['ingredients_hash'], unique=False)
    op.create_index(op.f('ix_recommendation_requests_session_id'), 'recommendation_requests', ['session_id'], unique=False)
    op.create_table('saved_recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'recipe_id', name='uq_saved_recipes_session_recipe')
    )
    op.create_index(op.f('ix_saved_recipes_recipe_id'), 'saved_recipes', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_saved_recipes_session_id'), 'saved_recipes', ['session_id'], unique=False)
    op.create_table('recommendation_request_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_request_id', sa.Uuid(), nullable=False),
    sa.Column('fridge_item_id', sa.Uuid(), nullable=False),
    sa.Column('freshness_status', sa.String(), nullable=False),
    sa.CheckConstraint("freshness_status IN ('fresh', 'near_expiry', 'expired')", name='ck_recommendation_request_items_freshness_status'),
    sa.ForeignKeyConstraint(['fridge_item_id'], ['fridge_items.id'], ),
    sa.ForeignKeyConstraint(['recommendation_request_id'], ['recommendation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_request_items_fridge_item_id'), 'recommendation_request_items', ['fridge_item_id'], unique=False)
    op.create_index(op.f('ix_recommendation_request_items_recommendation_request_id'), 'recommendation_request_items', ['recommendation_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_request_items_recommendation_request_id'), table_name='recommendation_request_items')
    op.drop_index(op.f('ix_recommendation_request_items_fridge_item_id'), table_name='recommendation_request_items')
    op.drop_table('recommendation_request_items')
    op.drop_index(op.f('ix_saved_recipes_session_id'), table_name='saved_recipes')
    op.drop_index(op.f('ix_saved_recipes_recipe_id'), table_name='saved_recipes')
    op.drop_table('saved_recipes')
    op.drop_index(op.f('ix_recommendation_requests_session_id'), table_name='recommendation_requests')
    op.drop_index(op.f('ix_recommendation_requests_ingredients_hash'), table_name='recommendation_requests')
    op.drop_table('recommendation_requests')
    op.drop_index(op.f('ix_interaction_logs_session_id'), table_name='interaction_logs')
    op.drop_index(op.f('ix_interaction_logs_recipe_id'), table_name='interaction_logs')
    op.drop_index(op.f('ix_interaction_logs_event_type'), table_name='interaction_logs')
    op.drop_index(op.f('ix_interaction_logs_created_at'), table_name='interaction_logs')
    op.drop_table('interaction_logs')
    op.drop_index(op.f('ix_fridge_items_session_id'), table_name='fridge_items')
    op.drop_index(op.f('ix_fridge_items_ingredient_id'), table_name='fridge_items')
    op.drop_table('fridge_items')
    op.drop_index(op.f('ix_user_sessions_anonymous_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_ingredient_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_llm_cache_ingredients_hash'), table_name='llm_cache')
    op.drop_table('llm_cache')
    op.drop_index(op.f('ix_ingredients_normalized_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_is_top'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_anonymous_users_browser_uuid'), table_name='anonymous_users')
    op.drop_table('anonymous_users')
    # ### end Alembic commands ###
